### ISSUE TITLE
Unable start the start the application when cloned

### ISSUE THREAD

**Issue by d-georgiev-91** [IgniteUI/warehouse-js-blocks#12]
### Description  
Typescript compilation error is thrown:
_node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'._

### Steps to reproduce  

1. Download/clone the repo
2. Run _npm install_ command
3. Run _npm start_ command

### Result  
Compilation error is thrown

### Expected result  
The samples should run.

---------------------------------------
There is an [issue](https://github.com/ReactiveX/rxjs/issues/2612) in rxjs, the depencencies should be configured to working version so the app can be built.

**Comment by rmkrmk** [comment]
The application is completelly refactored and is now using Angular 6 and IgniteUI-Angular 6 and should be working fine.
