### ISSUE TITLE
Refactoring of the Warehouse Sample

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/warehouse-js-blocks#13]
The warehouse showcase application is currently strictly mobile only. 

Redesign it to be suitable for full screen desktop viewing experience so it totally **rocks**.

**Comment by IG-Stanimir-Dimitrov** [comment]
@SDinev, the app design should have viewport mockups for 1024px (tablet) and 1366px (desktop) resolutions.

**Comment by rmkrmk** [comment]
The application is refactored and is working on any resolution.
