### ISSUE TITLE
Delete order through swipe

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/warehouse-js-blocks#2]
Currently orders cannot be deleted with swipe gesture.

**Comment by SDinev** [comment]
Can we, additionally, make a swipe gesture with "complete". Those could serve as shortcuts to quickly cancel or complete an order. 
Two ways to do this:
1. swipe left to delete/swipe right to complete (like tinder)
2. swipe to the left to uncover 2 buttons (like in mail)

**Comment by IG-Stanimir-Dimitrov** [comment]
Option 1 is more aligned with the material design guidelines and provides a quick action so it looks like the better option. It will also allow developers to assign a pop-up menu to the left swipe in case more than one action is available.

**Comment by SDinev** [comment]
Designed swipe gestures for the list. The two current actions are: 
1. quick complete, which marks all ticks inside of the list and moves the item to "archive" tab
2. cannot complete, which puts the list item in the "archive" tab under incomplete orders

In both cases a snackbar appears from below to allow the user to "undo" the action.

![01_startpage_search](https://cloud.githubusercontent.com/assets/13866657/20890759/b6bc91c4-bb10-11e6-8af4-37bdadfa5600.png)
![01_startpage_affirmativeaction](https://cloud.githubusercontent.com/assets/13866657/20890758/b6bb221c-bb10-11e6-9ac6-53b1ca3f62f0.png)
![01_startpage_negativeaction](https://cloud.githubusercontent.com/assets/13866657/20890757/b6b8d5de-bb10-11e6-8fd6-f09c1004b664.png)

@simeonoff created the animated high-fidelity prototype
![home - item interaction](https://cloud.githubusercontent.com/assets/13866657/20890822/0969ec78-bb11-11e6-9aa6-1561732d6a0c.gif)
