### ISSUE TITLE
Improvements for Search bar on list in "Active" 

### ISSUE THREAD

**Issue by SDinev** [IgniteUI/warehouse-js-blocks#38]
The search bar in the list in "Active" currently looks like this:
![current_state](https://user-images.githubusercontent.com/13866657/37456476-2d4eebfc-2848-11e8-8af2-67682c3fabd4.png)

Instead, it has to look and function like this:
![list_search](https://user-images.githubusercontent.com/13866657/37456156-6419d1e8-2847-11e8-881f-acd87b8ebb2d.png)

Reference:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/list.html

**Comment by rmkrmk** [comment]
Search bar is redesigned.
