### ISSUE TITLE
Add empty state

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/warehouse-js-blocks#4]
Add an empty state in the app list that is returned to the end user when a search does not display any results. 

https://github.com/IgniteUI/igniteui-js-blocks/issues/161

**Comment by SDinev** [comment]
Submitting design option for empty state; It follows the design pattern of the onboarding screens - a larger bolder headline and a smaller, secondary explanatory text.

![01_startpage_search_emptystate](https://cloud.githubusercontent.com/assets/13866657/20975921/9a0af8aa-bca9-11e6-86bb-9366706854ed.png)

**Comment by rmkrmk** [comment]
Done
