### ISSUE TITLE
Completed orders should have all items within marked as complete

### ISSUE THREAD

**Issue by SDinev** [IgniteUI/warehouse-js-blocks#41]
By design, the Archive section has 2 states for an order - completed or incomplete. 

Each item within a **completed** order needs to have all its items ticked. 
An **incomplete** order can have some items unticked.

Missing is the "Send to Active" button, which is useful in case an order is incomplete, but the user wants to complete it.

![completed order](https://user-images.githubusercontent.com/13866657/37461403-e87c75b2-2856-11e8-97f4-476572fa9160.png)
![screen shot 2018-03-15 at 13 45 15](https://user-images.githubusercontent.com/13866657/37461565-66f1b966-2857-11e8-87b4-a379f80aaa22.png)

**Comment by rmkrmk** [comment]
This looks like a bug with the igx-checkbox control - submitting an issue:
IgniteUI/igniteui-angular#872

**Comment by rmkrmk** [comment]
All orders in the "completed" list now have their items checked.
The "Send to active" button is now available in the "Incompleted" list.
