### ISSUE TITLE
Use igx-navbar in the app

### ISSUE THREAD

**Issue by SDinev** [IgniteUI/warehouse-js-blocks#42]
Instead of a custom-made navbar, use igx-navbar.
![navbar](https://user-images.githubusercontent.com/13866657/37461806-5c1290be-2858-11e8-8768-17e22fa41e4a.png)

![igx-navbar](https://user-images.githubusercontent.com/13866657/37461868-8f911b68-2858-11e8-810f-0adc17fc9c62.png)

https://www.infragistics.com/products/ignite-ui-angular/angular/components/navbar.html

**Comment by rmkrmk** [comment]
Done.
