### ISSUE TITLE
Archive list doesn't have completed/incomplete sections

### ISSUE THREAD

**Issue by SDinev** [IgniteUI/warehouse-js-blocks#43]
By design, the Archive list has completed and incomplete sections (complete with headers). this helps the users understand what they still have as incomplete.

![archive-complete-incomplete](https://user-images.githubusercontent.com/13866657/37461980-fa5afca2-2858-11e8-8865-22204316c37e.png)

**Comment by rmkrmk** [comment]
The application supports Completed and Incomplete sections in the Archive tab.
![image](https://user-images.githubusercontent.com/11978058/38087129-a29f61a8-335f-11e8-9946-71ad678198b5.png)
