### ISSUE TITLE
Add progress bar component to the application

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/warehouse-js-blocks#5]

**Comment by SDinev** [comment]
Designed progress bar for the main screen list; 
Depending on the percentage of completion of the list item, the progress bar changes color - starting from red, passing through yellow, and getting to green.
![01_startpage_search](https://cloud.githubusercontent.com/assets/13866657/20889436/be371b4a-bb0b-11e6-99ad-307a6ea7895e.png)
