### ISSUE TITLE
Application onboarding - design

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/warehouse-js-blocks#6]
Introduce an onboarding process to the warehouse application.

The user should get a pop-up carousel during the app launch that consists of three images telling the warehouse user story and app objectives.

**Comment by SDinev** [comment]
**Designed onboarding demo.** 
Its purpose is to set a main story for the app (for a richer experience) and help the user better understand what to click and why (improved usability of the app). 
![00_onboarding_1](https://cloud.githubusercontent.com/assets/13866657/20889829/2fcf555a-bb0d-11e6-9f62-0b3da53a3123.png)
![00_onboarding_2](https://cloud.githubusercontent.com/assets/13866657/20889830/2fe80988-bb0d-11e6-8ec0-33c4f14ca4e4.png)
![00_onboarding_3](https://cloud.githubusercontent.com/assets/13866657/20889832/2fee16fc-bb0d-11e6-8549-1acd5c15bd6d.png)
![00_onboarding_4](https://cloud.githubusercontent.com/assets/13866657/20889831/2fe887c8-bb0d-11e6-8daa-75fc99bff5db.png)

@simeonoff has created a high-fidelity prototype and exported an animation: 
![home - slider interaction](https://cloud.githubusercontent.com/assets/13866657/20889939/9f1e2472-bb0d-11e6-9662-e63ff37c3a7f.gif)

**Comment by SDinev** [comment]
Since there are no further comments on the design, texts and overall functionality, I'm closing the issue.
